import React from "react"

import Head from "next/head"

const BlogPage = () => {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Blog
    </div>
  )
}


export default BlogPage